# Generated by Django 3.0.6 on 2020-06-08 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20200607_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='name',
            new_name='goal',
        ),
        migrations.AddField(
            model_name='habit',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='habits.Habit'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='recorded_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
