# Generated by Django 3.0.6 on 2020-06-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20200608_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
