# Generated by Django 3.0.6 on 2020-06-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_dailyrecord_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('habit', 'recorded_on')},
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='user',
        ),
    ]
