# Generated by Django 3.0.6 on 2020-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_auto_20200611_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='recorded_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
